### ISSUE TITLE
Feature Request: Option to remove shadow

### ISSUE THREAD

**Issue by jedmao** [badgen/badgen#53]
GitHub doesn't like to display inline SVG, so it shows duplicated text because of the shadow feature. Be great if the shadow could be removed for this reason. Thanks for the great tool!

**Comment by amio** [comment]
🤔 how did you inlined the SVG?

**Comment by jedmao** [comment]
I generate my README files from AST and inline the result of calling badgen, which works fine for my docs site, but not GitHub or npm.

**Comment by jedmao** [comment]
I ended up just not using the generated SVG in my README.
