### ISSUE TITLE
Invalid icon have unexpected behavior

### ISSUE THREAD

**Issue by GMartigny** [badgen/badgen#54]
Hi,

When an invalid icon name is provided, the svg insert a corresponding badgen instance inside itself. It'll be more explicit with an example:

https://badgen.net/npm/v/express?icon=webpack
![image](https://user-images.githubusercontent.com/2543511/57020806-cde0d180-6c2a-11e9-9967-1d5709d173b2.png)

We can see the right `webpack` npm version display as icon here. It's quite odd and funny 😄.

**Comment by amio** [comment]
😂 Thanks for reporting
