### ISSUE TITLE
Badge for Apple iTunes / macOS / iOS App Store version

### ISSUE THREAD

**Issue by fregante** [badgen/badgen#69]
Can you add support for App Store versions?

Example from shields.io: ![](https://img.shields.io/itunes/v/1519867270.svg) 
(`https://img.shields.io/itunes/v/1519867270.svg`)

And its discussions: https://github.com/badges/shields/issues?q=iTunes+is%3Aissue

**Comment by amio** [comment]
We have an apple icon
 [![](https://badgen.net/badge/icon/apple?icon=apple&label)](https://badgen.net/badge/icon/apple?icon=apple&label)
