### ISSUE TITLE
This Serverless Function has crashed

### ISSUE THREAD

**Issue by OmgImAlexis** [badgen/badgen#70]
https://flat.badgen.net/badgesize/normal/https/unpkg.com/hydrate-text@1.2.7/dist/umd/index.min.js?label=Minified

The link above causes the following error. I sometimes get "badgen error" but for the most part I was seeing the 500.

<img width="613" alt="Screen Shot 2021-07-04 at 9 01 36 am" src="https://user-images.githubusercontent.com/6525926/124369024-8e005380-dca6-11eb-9342-c78925f7da06.png">

Related: https://github.com/vasilii-kovalev/hydrate-text/issues/22

**Comment by amio** [comment]
Looks like something wrong with badgesize service, just put an issue https://github.com/ngryman/badge-size/issues/94
