### ISSUE TITLE
Bug: Consecutive badges have a max width of the first ones actual width.

### ISSUE THREAD

**Issue by Albhe428** [badgen/badgen#71]
Hey, I have a problem with the library in the browser (v3.2.2). Whenever a badge is created all following badges have a max size on their graphics of the exact same size as the first badges width. The text still shows up but there is no color behind it (see the codepen and/or screenshot).

![image](https://user-images.githubusercontent.com/65772539/129530688-b1c4d824-8d4f-44f9-b21f-186f0a9f6913.png)

Codepen: https://codepen.io/abbeh13/pen/abWxMyb

**Comment by amio** [comment]
Strange, this issue occurs in Chrome v101 and Firefox v98, but not on Safari v15.4

**Comment by lj0812** [comment]
Could you please consider releasing the latest version? The version I installed through npm seems to have this bug.

**Comment by amio** [comment]
Hey @lj0812 @Albhe428 , I just released the fix in v3.2.3. Thanks!
